#!/usr/bin/env bash
# script to transfer a file from a client to the server
if [[ $# -ne 4 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/$1
fi
