#!/usr/bin/env bash
# redirects
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sed -i '/^\tserver_name.*/a\/trewrite ^\/redirect_me http:\/\/www.visualsatisfaction.com permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
