#!/usr/bin/env bash
# Installs Nginx listening on port 80
# shellcheck disable=SC2154
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html
cd usr/share/nginx/html/
sudo touch 404.html
sudo chmod 777 404.html
sudo echo "Ceci n'est pas une page" > 404.html 
sed -i '/^\tserver_name.*/a \\trewrite ^\/redirect_me https:\/\/www.youtube.com\/user\/thisissoawkward permanent;' /etc/nginx/sites-available/default
cd /etc/nginx/sites-available/
sudo chmod 644 default
sudo sed -i "36a \\\tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default
sudo service nginx restart
