#!/usr/bin/env bash
# Installs Nginx listening on port 80
# shellcheck disable=SC2154
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html
cd usr/share/nginx/html/
touch 404.html
echo "Ceci n'est pas une page" > 404.html 
sed -i '/^\tserver_name.*/a \\trewrite ^\/redirect_me https:\/\/www.youtube.com\/user\/thisissoawkward permanent;' /etc/nginx/sites-available/default
cd /etc/nginx/sites-available/
sed -i "36a \\\tadd_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default
service nginx restart
