#!/usr/bin/env bash
# installs a load balancer
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.7
sudo apt-get -y update
sudo apt-get install haproxy=1.7.\*
sudo echo "ENABLED=1" >> /etc/default/haproxy 
sudo cat >> /etc/haproxy/haproxy.cfg << EOF
frontend http_front
        bind *:80
        mode http
        default_backend http_back
  
backend http_back
        balance roundrobin
        server 1693-web-01 52.200.125.49:80 check
        server 1693-web-02 35.196.108.12:80 check
EOF

sudo service haproxy restart
