#!/usr/bin/env bash
# fizzbuzz
export i
i=1
for i in {1..100}
do
    if ! ((i%15))
	then
	echo "FizzBuzz"
    elif ! ((i%3))
    then
	echo "Fizz"
    elif ! ((i%5))
    then
	echo "Buzz"
    else
	echo "$i"
	i=$((i+1))
    fi
done
