#!/usr/bin/env bash
export i
i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]
	then
	echo "bad luck"
	i=$((i+1))
    elif [ $i -eq 7 ]
	then
	echo "good luck"
	i=$((i+1))
    else
	echo "Holberton School"
	i=$((i+1))
    fi
done
