#!/usr/bin/env bash
export i
i=0
while [ $i -lt 21 ]
do
    case $i in
	4)
	  echo "$i"
	  echo "bad luck from China"
	  i=$((i+1))
	;;
	9)
	  echo "$i"
	  echo "bad luck from Japan"
	  i=$((i+1))
	;;
	17)
	    echo "$i"
	    echo "bad luck from Italy"
	    i=$((i+1))
	;;
	*)
	  echo "$i"
	  i=$((i+1))
	;;
    esac
done
