#!/usr/bin/env bash
# clock
export i
export j
i=0
j=1
t=1
while [ $t -lt 14 ]
do
    echo "Hour: $i"
    while [ $j -lt 60 ]
    do
	echo "$j"
	j=$((j+1))
	if [ $i -eq 14 ]
	then
	    i=$((i+1))
	elif [ $j -eq 60 ]
	then
	    i=$((i+1))
	else
	    echo "$j"
	    j=$((j+1))
	fi
    done
    t=$((t+1))
    j=1
done
