#!/usr/bin/env bash
# clock
export i
export j
i=1
j=1
t=1
while [ $t -lt 13 ]
do
    while [ $j -lt 60 ]
    do
	echo "$j"
	j=$((j+1))
	if [ $j -eq 60 ]
	then
	    echo "Hour: $i"
	    i=$((i+1))
	else
	    echo "$j"
	    j=$((j+1))
	fi
    done
    t=$((t+1))
    j=1
done
