#!/usr/bin/env bash
# nginx user
sudo pkill apache2
sudo chmod -R 777 /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
